chore: unused-result error with write
error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]